In [1]:
import pickle as pk
import numpy as np

In [2]:
clf = pk.load(open('Models/clf.pkl','rb'))
ohe_embarked = pk.load(open('Models/ohe_embarked.pkl','rb'))
ohe_sex = pk.load(open('Models/ohe_sex.pkl','rb'))

In [3]:
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1,7)

In [4]:
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1,1))

C:\Users\PMYLS\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [5]:
test_input_sex

array([[0., 1.]])

In [6]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [7]:
test_input_embarked

array([[0., 0., 1.]])

In [9]:
test_input_transformed = np.concatenate((test_input[:,0].reshape(1,1), test_input_sex, test_input[:,[2,3,4,5]], test_input_embarked), axis=1)

In [10]:
test_input_transformed.shape

(1, 10)

In [11]:
clf.predict(test_input_transformed)

array([1], dtype=int64)